server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://localhost:3306/leyou
    username: root
    password: root
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  #保证拿到的一定是本地地址
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1